modLoader="javafml"
loaderVersion="[47,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="ui_utils_forge"
version="${file.jarVersion}"
displayName="UI Utils"
displayURL="https://ui-utils.com"
logoFile=""
authors="Coderx_Gamer, MrBreakNFix"
description="Plugin debugging mod for Minecraft Forge"

[[dependencies.ui_utils_forge]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.ui_utils_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"
